"""empty message

Revision ID: b84d2f333990
Revises: 38ef52fef2e6
Create Date: 2021-04-23 01:05:38.560716+09:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b84d2f333990'
down_revision = '38ef52fef2e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_status_priority', 'tasks', ['status', 'priority'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_status_priority', table_name='tasks')
    # ### end Alembic commands ###
